wrappers/hnygorilla/gorilla.go, wrappers/hnygorilla/gorilla_test.go
We use structs for our handlers. Getting the function name will panic as a result. This corrects that.
=> Don't panic if the handler is a struct

examples/goji/main.go, examples/gorilla/main.go, examples/http_and_sql/main.go, examples/httprouter/main.go, examples/nethttpfunc/main.go, internal/internal.go, internal/internal_test.go
`req.URL.Host` doesn't appear to populate Honeycomb with an actual value. Switching to `req.Host` works in the case of 
* `curl localhost:8080/hello/hi`
* `curl -H "Host: example.com" localhost:8080/hello/hi`
**Testing**
=> Switch to using request.Host for getting the host header

wrappers/hnysqlx/sqlx.go
Using `context.Background()` in these functions was causing these trace spans to
become disconnected from their parent spans.
=> Use passed in context to build event

wrappers/hnysqlx/sqlx.go
Add a method so that when a transaction is comitted, the commit shows up as part of the trace instead of being orphaned.
=> Commit with context

trace/trace.go, trace/trace_test.go
Added test confirming that rolled up fields actually get set on the root span.  They didn't. Fixed the code so they do. Tests pass.  Yay!
=> fix rollup - fields should be added to the root span

version.go, wrappers/common/common.go
When trying to track down where I had missed threading context through an app to get to the db (having added the hnysqlx wrapper), I found it very difficult to tell from the SQL alone which call was missing the context thread. Adding the name of the function that called the sql function made it way nicer. 
eg:
```
db.call: GetContext
db.caller: FetchDatasetByID     <--- super useful
```
=> knowing which sql function is called is nice; knowing who called it is nicer.

CHANGELOG.md, version.go
to be landed after #24 and #25, assuming both get approved eventually.
=> bump version, update changelog

wrappers/hnyhttprouter/httprouter.go, wrappers/hnyhttprouter/httprouter_test.go
`handle()` is called with the original `ResponseWriter` and not the wrapped `ResponseWriter`. So when the httprouter.Handle is called, the `Status` field on the writer is not touched. As a result, the middleware always emits `200` as the status code.
=> Fix hnyhttprouter to pass wrapped ResponseWriter to handler

CHANGELOG.md, beeline.go, version.go
Libhoney's default configuration for batch goroutine count is pretty high (at 80), as is the config for PendingWorkCapacity. If the application is memory constrained, this could become an issue, especially if there are ingestion issues in the API, as events can pile up in the queue and the number of in flight-batches can max out. This diff sets some lower defaults, and adds configuration variables for overriding these values if desired.
=> Allow override of event batching configuration in libhoney

wrappers/common/common.go, wrappers/common/common_test.go
As part of the v1 -> v2 beeline I thought "having `db.call` repeated as `name` is redundant. But the Honeycomb UI defaults to using `name` as the span identifier so having it blank leads to traces that look like this:
This change adds them back in - db.call is duplicated as `name`.
=> add name back in as db call

doc.go
beeline.Init doesn't take a reference. Bumped into this setting it up so I wanted to send back the doc update.
=> Update example to fix beeline.Init

wrappers/common/common.go, wrappers/common/common_test.go, wrappers/hnygoji/goji.go, wrappers/hnygorilla/gorilla.go, wrappers/hnyhttprouter/httprouter.go, wrappers/hnynethttp/nethttp.go
* Use the ResponseWriter returned from httpsnoop.Wrap so that optional methods are still exposed on the concrete type.
* Only record the first set status code.
I'm not sure `ResponseWriter` is a good name for the struct anymore. I considered renaming it to `ResponseRecorder` but didn't want to make too many changes.
Resolves #18
=> Prevent obscuring optional http.ResponseWriter methods.

.travis.yml, trace/trace.go, trace/trace_test.go
This resolves https://github.com/honeycombio/beeline-go/issues/34 by adding a lock around the children slice on each span. I also turned on the race detector in CI. Prior to fixing the races, the test output was
```
$ go test ./trace -race
==================
WARNING: DATA RACE
Write at 0x00c0002ba008 by goroutine 30:
github.com/honeycombio/beeline-go/trace.(*Span).CreateChild()
/Users/mikeatkins/go/src/github.com/honeycombio/beeline-go/trace/trace.go:283 +0x27d
github.com/honeycombio/beeline-go/trace.(*Span).CreateAsyncChild()
/Users/mikeatkins/go/src/github.com/honeycombio/beeline-go/trace/trace.go:270 +0x50
github.com/honeycombio/beeline-go/trace.TestCreateAsyncSpanDoesNotCauseRaceInSend.func2()
/Users/mikeatkins/go/src/github.com/honeycombio/beeline-go/trace/trace_test.go:233 +0x4c …
```
=> Asyncchild race

trace/trace.go
`CreateChild` adds a new span to the current span's list of children. `CreateAsyncChild` calls `CreateChild`, then sets the isAsync bool on the span. This can lead to a race caused by simultaneous read of the child span's `isAsync` bool by `Send` as it's being written by `CreateAsyncChild`. To fix this, I refactored  the code a bit to allow us to set `isAsync` before the span is added to the list of child spans.
This doesn't seem to be the same race reported in https://github.com/honeycombio/beeline-go/issues/38 but it should be fixed either way.
=> [trace] Fix race between CreateAsyncChild and span.Send

trace/trace.go, trace/trace_test.go
Fixes https://github.com/honeycombio/beeline-go/issues/38  - if `Send` is called for a span and its parent at the same time, a race can occur when accesing "isSent". This adds a lock to `Send`, which sets `isSent` and protects reads with read locks. This also effectively prevents `Send` from executing multiple times for the same span.
=> [trace] fix race when child and parent send is called at the same time

wrappers/hnynethttp/nethttp.go, wrappers/hnynethttp/nethttp_test.go
The other status codes in this file are returned with the field name `resp.status_code`; this one should not be an odd duckling. =\ (Will defer to you wrt how we roll this out.)
Also added to the tests to convince myself that the response status code is in fact being set correctly.
=> fix field name parity between resp.status_code and response.status_code

wrappers/common/common.go, wrappers/hnynethttp/nethttp.go
There was nothing in the beeline that would show you the full URL requested. This adds that under `request.url` and also adds just the query portion of the URL at `request.query`. The URL is close to path + query, but is actually more - anchors (#foo) will appear in the URL but aren't explicitly called out into their own field here.
=> add url queries, add name even when empty

propagation/propagation.go, propagation/propagation_test.go, trace/trace.go, trace/trace_test.go, version.go
if `NewTrace()` is given headers, uses the dataset of the parent trace rather than the default. This should make life easier in environments with more than one tracing dataset. Also, more determined users like myself could even, hypothetically, cook their own Propagation and use it to overcome this limitation of the API.
=> Propagate dataset in serialized headers

trace/context.go, trace/context_test.go
When breaking context to isolate a section of code from a timeout or cancellation in its parent, it's necessary to create a new context for the isolated code. Copying the context bits that are necessary to continue the beeline trace is annoying; this function makes it a little bit easier.
=> add a convenience function to copy the trace bits from one context to another

propagation/propagation.go, propagation/propagation_test.go, trace/trace.go, trace/trace_test.go, version.go
One real bugfix here: previously, if you handed NewTrace() a broken header, you'd end up with a trace with an empty traceID.
More controversially, I also allow partial propagation structs, which shouldn't actually occur with the current codebase. I think this is a safe change to make and actually lets me manually set the Dataset, which I was attempting with my previous change.
=> improve handling of incomplete or broken serialized headers

CHANGELOG.md, trace/trace.go, version.go
The multiplication of sample rate here is incorrect. It came from an assumption that `ev` could have already been sampled, but the code makes using a sampler hook an _alternative_ to the global sample rate, not in addition to it. Since sampling only happens once, the rates should not be multiplied.
=> ev can't have been already sampled here so multiplying is incorrect

propagation/propagation.go
We added a dataset field to the header to allow downstream services that serve different functional groups send the related spans to the right place. We neglected to update the comment describing the header.
=> add comment describing additional 'dataset' parameter to trace header

trace/trace.go, trace/trace_test.go
This patch makes sure that before checking how many children a span has; when calling `send()`; we will hold the `childrenLock` to avoid a data race if another goroutine is at the same time creating a new span and writing to `s.children`.
The lock is held here: https://github.com/honeycombio/beeline-go/blob/015109f8347c1922dcc0cc3b96d706c24fd96ef8/trace/trace.go#L438-L440
But when checking how many items the slice contains the lock is not held: https://github.com/honeycombio/beeline-go/blob/015109f8347c1922dcc0cc3b96d706c24fd96ef8/trace/trace.go#L389
=> Fix data race for children spans.

beeline.go
This fixes #60 by adding a config option and default for `BatchTimeout` and passes it to `transmission.Honeycomb`.  If this is 0, `muster` doesn't send events on a timer: https://github.com/facebookarchive/muster/blob/master/muster.go#L65-L68
At the moment, there are 3 places that the `transmission.Honeycomb` struct is created:
- `beeline.Init` https://github.com/honeycombio/beeline-go/blob/master/beeline.go#L120-L125
- `libhoney.NewClient` https://github.com/honeycombio/libhoney-go/blob/master/client.go#L85-L93 (only if one is not passed in)
- `libhoney.Init` https://github.com/honeycombio/libhoney-go/blob/master/libhoney.go#L207-L218 (only if one is not passed in)
I considered trying to unify these, but I didn't want to introduce changes across both libraries, so opted for the …
=> Fix events not firing on a timer: add `BatchTimeout`

sample/deterministic_sampler_test.go
Go is the reference implementation for deterministic sampling, so it makes sense to start here. Adds a test with a specific set of determinants and values - other beelines will test against this same set to ensure the same output.
=> [sample] add interop test

wrappers/hnysql/sql.go, wrappers/hnysqlx/sqlx.go
When we pass it as an arg, it's evaluated at `defer`-time.  This means we'll never send a non-nil error.
Closing over it instead should allow it to be updated and we'll send the right thing.
=> defer a function so we can close over err instead of passing it as an arg

.circleci/config.yml, README.md
It's totally conceivable that 1.9 still works if you have older pinned versions of our deps, but `go get` is fetching newer ones which don't even compile on 1.9.
=> drop go1.9 tests, since deps have updated beyond it

wrappers/hnysqlx/sqlx.go
All the functions that get context are supposed to use that context to join the events created to existing traces as spans. Functions that don't have context use the event-version of the instrumentation instead.
This instances of the QueryxContext function accidentally used the event version instead of the span version.  This change fixes that error.
=> [sqlx] functions with context should use spans; this one was skipped

wrappers/hnysqlx/sqlx.go
This can be useful when you want to use APIs that are not a part of the standard DB API.
In my specific case I want to use `pgx`'s `COPY FROM` support, which requires me to access the underlying `pgx` conn.
=> hnysqlx: Provide a method for accessing the inner DB

wrappers/hnynethttp/nethttp.go
As [suggested](https://app.slack.com/client/T4T3A2T63/CLXQWT35J/thread/CLXQWT35J-1576638751.004200) by @maplebed. Seemed to make sense to do `WrapHandler*` too, but feel free to drop that if you don't like it.
=> Add response.content_{length,type} in RoundTripper/WrapHandler*

trace/trace.go
- add getter methods to the Trace and Span structs
allowing r/o access to the ID strings (e.g. for logging)
- add a GetTrace() method to the Span struct, allowing
clients to chase up the tree that way
=> Add getter methods for trace/span/parent IDs

wrappers/hnypop/pop.go
It looks like the pop example has been broken since [this change](https://github.com/gobuffalo/pop/commit/589293a65af37b78c92ed0a80852c48ab82974b5#diff-1ac94134b8964626aaac00790fa9b48f). Because the example code wasn't compiling, `go test` was returning a non-zero status code despite all of our tests technically passing.
=> Add context methods to DB. Fixes pop example.

wrappers/common/common.go, wrappers/hnysqlx/sqlx.go
When adding an `error` type to a span, the effect is that you get the JSON serialized version of an interface type which is `{}`. This is not super useful. This change explicitly asks for the string representation of the error instead of throwing in the error type, resulting in better content in the error field.
=> [sqlx] Adding an error interface does not stringify by default. Explicitly use the error string

trace/trace.go, trace/trace_test.go
The [W3C Trace Context](https://www.w3.org/TR/trace-context/) specification defines span ids as 8-byte arrays and trace ids as 16-byte arrays. In order to maintain compatibility with other services using that standard, we should start generating our ids in the same way. This will make it easier to add trace propagation interoperability between OpenTelemetry and Beeline instrumented services.
This is part of a series of PRs meant to replace #108.
=> Replace UUID strings with W3C Trace Context compatible IDs.

propagation/honeycomb.go, propagation/propagation.go, propagation/propagation_test.go, trace/trace.go, trace/trace_test.go
In preparation for adding support for different trace propagation wire formats, this PR generalizes PropagationContext to include fields found in all of the formats we plan to support. It also renames generic functions like `MarshalTraceContext` to the more specific `MarshalHoneycombTraceContext`. (In future PRs we plan to introduce marshal / unmarshal functions for other trace header formats). The old function names are left as wrappers and are marked as deprecated.
This also adds a `NewTraceFromPropagationContext` function to the `trace` package. This function will be used to create traces from newly parsed headers but, unlike `NewTraceFromSerializedHeaders`, has no knowledge of the header format itself. `NewTrace` wraps `NewTraceFromSerializedHeaders` but may in the future change to …
=> Generalize PropagationContext and Related Methods

propagation/propagation_test.go, trace/trace.go, trace/trace_test.go, wrappers/common/common.go, wrappers/config/config.go, wrappers/hnynethttp/nethttp.go
Allow users of the beeline to create custom hooks that define how
request headers can be mapped to propagation context on incoming HTTP
requests and how a propagation context can map to trace context headers
on outgoing HTTP requests.
The parser hook is used for incoming requests and is therefore passed to
the `WrapHandlerWithConfig` function in the `hnynethttp` package:
```
import (
....
"github.com/honeycombio/beeline-go/wrappers/config"
)
// Parse incoming AWS headers (e.g. from a load balancer)
func traceParserHook(r *http.Request) *propagation.PropagationContext {
header := r.Header.Get("X-Amzn-Trace-Id")
prop, err := propagation.UnmarshalAmazonTraceContext(header)
if err != nil {
...
}
return prop
}
log.Fatal(http.ListenAndServe(":8000", hnynethttp.WrapHandlerWithConfig(mux, …
```
=> Create trace parser and propagation hooks.

propagation/amazon.go, propagation/propagation_test.go
AWS headers are propagated when a service call is expected to cross an
ALB or ELB in between service boundaries. Amazon load balancers will
respect the value sent in the Parent segment of the X-Amzn-Trace-Id
header and log the value as the parent of the request.
Additionally, modify the parsing logic so that if Parent and Self are both
present in an Amazon header, respect Self since it comes from the load
balancer. If Parent is present and Self is not, use Parent. If neither are
present, but Root is, use it as the trace and parent ID.
=> Include Parent segment, not Self when sending AWS headers.

CHANGELOG.md, CONTRIBUTORS, version.go
- Generated Span and Trace IDs have changed from UUID4 strings to 16 and 32 character hex encoded strings. These are compatible with the W3C Trace Context specification.
- Auto-instrumentation support for Gingonic applications (thank you @Nalum!)
Marshal / unmarshal functions for Amazon load balancer trace headers and W3C Trace Context headers (used by OpenTelemetry).
- The hnynethttp package now supports configurable hooks for parsing trace context headers from incoming HTTP requests and injecting trace context headers in outgoing HTTP requests
=> Bump version to v0.6.0

propagation/honeycomb.go, propagation/propagation_test.go
The `IsValid()` function on `propagation.PropagationContext` is intended to
validate `PropagationContext` objects that are either created from
incoming trace context headers, or used to generate outgoing trace
context headers. In either case, the context had better contain a
`ParentID` or it is not valid.
There is a use case, however, with Honeycomb headers, where a user of
older beeline versions would create a `PropagationContext` (aliased as
`Propagation`) manually, and then serialize it as a Honeycomb header to
create a new `trace.Trace`. In this case, the `PropagationContext` would not
necessarily have a `TraceID` or a `ParentId`, and so it would fail `IsValid`.
=> Disable validation check on Unmarshal for Honeycomb headers

propagation/propagation_test.go
While exploring propagation I realized there were a number of cases that weren't explicitly covered by the round trip tests. This addition gives a nice set of examples-via-code of what sort of serialized strings we should expect from different versions of incoming propagation contexts.
=> adding tests for marshaling the honeycomb beeline header

propagation/honeycomb.go
The example header in the honeycomb propagator has an invalid context value. The context should be a base64 encoded json object that is translated into a map as trace fields. However, the current example is a simple encoded string.
Current base64 value: `Hello World`
Updated base64 value: `{"hello":"world"}`
Closes #147.
=> Update example honeycomb header

wrappers/hnysqlx/sqlx.go, wrappers/hnysqlx/sqlx_test.go
This is a straight copy from `Tx.BindNamed` so that we can access `DB.BindNamed`.
=> Add DB.BindNamed based on Tx.BindNamed

CHANGELOG.md, version.go
Updates beeline-go to v0.10.0 and updates changelog.
=> Prepare v0.10.0 release

.circleci/config.yml
In order to have CirlceCI push draft releases to github there is a separate API token that allows pushing artifacts. We set up a separate CircleCI context that has an API token with that right. Trying it out to see if it works!
=> Use separate CircleCI context for public repositories

go.mod, propagation/honeycomb.go, wrappers/config/config.go, wrappers/hnygrpc/doc.go, wrappers/hnygrpc/grpc.go, wrappers/hnygrpc/grpc_test.go
This allows users to instrument gRPC services by providing a wrapped interceptor when creating a server:
```
serverOpts := []grpc.ServerOption{
grpc.UnaryInterceptor(hnygrpc.UnaryServerInterceptorWithConfig(...)),
}
server := grpc.NewServer(serverOpts...)
```
Note that at the moment, only unary RPCs are supported. Streaming gRPC clients and servers can be added later. Outgoing instrumentation is also not supported yet, hence no `config.GRPCOutgoingConfig` or propagation hook included in this PR.
=> Adding a gRPC interceptor wrapper.

trace/trace.go, trace/trace_test.go
The current implementation of rollup fields will only add them to spans
that are marked as `root` spans. Spans are only labelled as "root" when
they created the trace, and have no parent. Spans that are created from
a trace's propagation context are instead marked as `subroot`.
Unfortunately this means that other apps participating in the trace are
unable to utilize rollup fields, as the root of their in-process trace
will never be `root`.
This commit tweaks the trace's `Send()` function to allow rollup fields
to be added to `subroot` spans.
Ben mentioned that the `meta.span_type` field may be deprecated at some
point (and presumably `spanType` along with it), so it seemed better to
rely on the span's internal `isRoot` boolean for deciding on whether
rollup fields should be added. …
=> Ensure rollup fields are included on subroot spans

propagation/propagation_test.go, trace/trace.go
Receiving OTEL instrumentation ignores spans coming with the 00 sampled flag.
This is a stop-gap measure to ensure w3c parser hooks work with an OTEL receiver. Ideally, we would like to set the sampled flag based on an actual sampler, but that requires further investigation.
We can't default the `TraceFlags` in the actual `w3c.MarshalW3CTraceContext` because by then we can't differentiate the zero-value `PropagationContext.TraceFlags` from an actual `00` flag. Making `TraceFlags` a pointer (or something similar) would break the public interface.
Since `PropagationContext.TraceFlags` is currently only consumed by `w3c.MarshalW3CTraceContext`, it seemed _OK_ to do it here.
=> Default w3c sampled flag to 01

.github/dependabot.yml, .github/workflows/apply-labels.yml
Also tell dependabot to label PRs as maintenance.
=> add our custom action to manage project labels

wrappers/hnygorilla/gorilla.go
Fixes #164.
The hnynethttp wrapper adds fields for response headers other than the status code, and the same would be useful in the hnygorilla wrapper:
https://github.com/honeycombio/beeline-go/blob/5f09432b6f3de0e6107f87d25a134b95bd94850a/wrappers/hnynethttp/nethttp.go#L67-L75
=> Set additional response header values in hnygorilla wrapper

beeline.go, propagation/propagation.go, propagation/propagation_test.go, trace/context_test.go, trace/trace.go, trace/trace_test.go, wrappers/common/common.go, wrappers/hnygrpc/grpc.go
Update propagation deprecations:
* NewTrace now takes a propagationContext instead of Headers
=> Remove deprecated wrappers in prep for major release

wrappers/common/common.go, wrappers/common/common_test.go
I've found that when using `hnynethttp.WrapRoundTripper`, the `request.host` property is left empty on spans generated  when the http client follows 3xx redirects (as when making a GET request to a shortened URL). This change ensures that the `request.host` property populated as expected on those spans.
This snippet from the documentation for the `URL` field on the [`http.Request` struct](https://golang.org/pkg/net/http/#Request) helps explain why `req.Host` is often empty on client requests (emphasis added):
> // For client requests, the URL's Host specifies the server to
> // connect to, while the Request's Host field **_optionally_**
> // specifies the Host header value to send in the HTTP
> // request.
=> Capture correct request.host value on http client redirects

.circleci/config.yml, go.sum
* Add missing entry in go.sum
* Since go 1.16, go.mod and go.sum are no longer automatically fixed: https://blog.golang.org/go116-module-changes#TOC_3.
* CI was passing on 1.16, because we were doing `go mod download` before running the tests, which was updating the go.sum
* Now it will fail: https://app.circleci.com/pipelines/github/honeycombio/beeline-go/752/workflows/e50bcef6-52fc-4674-a516-148ff9e07930/jobs/2363
* Fixes #226
=> Fix go.sum and CI

CHANGELOG.md, version.go
Sets version to `1.1.3` and updates changelog with changes since 1.1.2 release.
=> Prepare 1.1.3 release

wrappers/hnyecho/echo.go, wrappers/hnyecho/echo_test.go, wrappers/hnyecho/hnyecho_test.go
This follows the pattern implemented in the opentracing echo middleware which ensures the registered error handler is invoked prior to completing the trace, otherwise echo doesn't capture the actual response code to the client.
For reference this is the opentelementry code https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/github.com/labstack/echo/otelecho/echo.go#L79-L92
I have included a test which demonstrates the problem.
=> fix(echo): this change ensures honeycomb captures errors correctly

beeline.go, trace/trace.go, trace/trace_test.go
Small tweak to allow `span.AddField()` to support adding error types, similar to `beeline.AddField()`.
=> feat: span.AddField() support adding error

go.mod, go.sum
Updates libhoney-go to latest [v1.15.6](https://github.com/honeycombio/libhoney-go/releases/tag/v1.15.6).
- Updates libhoney-go dependnecy in go.mod/sum
=> Update libhoney-go to v1.15.6

wrappers/hnygrpc/grpc.go, wrappers/hnygrpc/grpc_test.go
When looking at traffic instrumented with `hnygrpc`, I break down by `handler.method` and `response.grpc_status_code`. This is all well and good, but what I get back for the status code is 0,12, 16. 
While HTTP has been around long enough that many folks know what 200 and 404 mean, I don't have the same drilled-in understanding of what grpc codes 12 and 16 are. (turns out, `Unimplemented` and `Unauthenticated`. [reference](https://pkg.go.dev/google.golang.org/grpc@v1.40.0/codes#Code))
To aid the people using this instrumentation, this change augments `response.grpc_status_code` with `response.grpc_status_message` that contains the `.String()` version of the code, so people can see `Unimplemented` next to `12` when looking at their responses.
=> [hnygrpc] add a human readable version of the grpc status code to auto instrumentation

propagation/w3c.go, wrappers/common/common.go, wrappers/common/common_test.go
- closes #286 
- preference: parser hook > honeycomb > w3c
=> parse incoming w3c header by default

CHANGELOG.md, version.go
- Bump version and update changelog for release.
=> Prepare v1.4.0

go.mod, go.sum, version.go
Bumps libhoney dependency.
- Bumps libhoney-go to v1.15.8
=> bump libhoney-go to v1.15.8

wrappers/hnysqlx/sqlx.go
- This is a followup to #301. I missed adding the same method to the `Tx` object. This resolves a mismatch that was accidentally introduced between `DB` and `Tx` (these should be the same). 
- Adds a `RebindContext(ctx, query)` method to the `Tx` object.
=> Add RebindContext method to Tx struct

beeline.go, trace/context.go, trace/trace.go
- Implements the Honeycomb Beeline equivalent of the tracer to profiler data passing in [Pyroscope's demo PR](https://github.com/pyroscope-io/pyroscope/pull/766/files#diff-3bca24a7cb36f4a461afa30d9dc6b389b3e699d5c89710040b1121d162df1943R224)
Thanks to @kolesnikovae @petethepig and @Rperry2174 for your partnership so far!
=> feat: pass process root span id as pprof profile id tag

trace/context.go, trace/trace.go
Fixes bug in #305 where previous pprof context wouldn't get restored after span end in case goroutine is reused for something else.
=> fix: preserve previous pprof labels after span end

beeline.go
E&S changes print error messages to stdout; this moves them to stderr.
I didn't change the error message for beelines configured to STDOUT; that one seems like it's meant to be part of the debug stream.
Found references from #309 to `fmt.println` and changed to `fmt.Fprintln( os.stderr )`
`go test` continues to work, but seems to print the error messages to stdout still -- but that might be `go test` quirk? (Verified -- when I actually use this is in code, it works as expected.)
=> output error messages to stderr

.circleci/config.yml, beeline.go
- go 1.18 was released earlier this month
- add 1.18 to test matrix
- 1.18 failed `./beeline.go:177:4: fmt.Println call has possible formatting directive %s`
- removed the warning color altogether, we're not using it for any other warnings
- update default version to 1.18
- bump go orb
=> maint: add go 1.18 to CI

CHANGELOG.md, README.md, go.mod, version.go
Prep for release of 2.0.0. Requires #314 first.
=> Prep for release

go.mod, go.sum
Resolves #337
- Having an incompatible version of go-sqlite3, breaking other dependencies in my code
Removed `go-sqlite3` from go.mod, ran `go mod tidy`.
=> Downgrade go-sqlite3 to stable version

wrappers/hnygrpc/grpc.go, wrappers/hnygrpc/grpc_test.go
- Closes #339 
- Adds the following fields to a GRPC handler span:
- request.header.x_forwarded_for
- request.header.x_forwarded_proto
- request.remote_addr
- Refactored the existing if-chain to a loop of headers to check and add to span if present.
=> Add more request header information to GRPC handler spans

.circleci/config.yml, README.md, go.mod
This PR drops support for Go 1.16, it's more than two versions old and we're running into dependency update issues by continuing to support it.
- Remove 1.16 from circleci test matrix
- Update README
- Update go.mod
=> [maint] Drop support for go 1.16

trace/trace.go
- Similar to https://github.com/honeycombio/libhoney-go/pull/197, profiling shows we spend a lot of time in github.com/honeycombio/beeline-go/trace.(*Span).send generating the map.
- define the map capacity in advance before returning it.
a subsequent follow-up might be allowing passing a map in its entirety to github.com/honeycombio/libhoney-go.(*Event).AddField so that the map entries do not need to be added one at a time when merging the maps together.
Or, better yet, https://github.com/golang/go/issues/56182 could prevent this problem by giving us a more sensible API for mass additions to a map.
=> pre-define capacities for rollups and TLFs

go.mod, go.sum
Bumps libhoney-go dependency.
- bumps libhoney-go to v1.19.0
=> maint: Bump libhoney to 1.19.0

beeline.go, beeline_test.go, trace/trace.go
- Closes #401 
There is a remarkable amount of memory allocation occurring under load to perform the "app." prefixing of field names by the Beeline.
This change skips the memory allocations needed for string concat and usage if the "app." prefix is already present on the field name provided.
Existing behavior is no slower or memory hungry, but for every field name provided by the Beeline user that starts with "app.", that is one less memory allocation of the size of the field name string.
```
BenchmarkBeelineAddField/oldAddField/whatever
BenchmarkBeelineAddField/oldAddField/whatever-12                19654003                60.52 ns/op            8 B/op          1 allocs/op
BenchmarkBeelineAddField/AddField/no-prefix
BenchmarkBeelineAddField/AddField/no-prefix-12                  18939754 …
```
=> perf: speed up adding fields, reduce memalloc if field name is already prefixed with "app."

CHANGELOG.md, version.go
Prepares the next release of beeline-go
- Add changelog entry
- Update version to 1.15.0
=> rel: Prepare 1.15.0 release

.github/dependabot.yml
Reduce the number of dependabot PRs
- Groups minor and patch dependency updates into a single group.
=> maint: group patch updates for go deps

.circleci/config.yml, README.md, go.mod
- sparked by https://github.com/honeycombio/beeline-go/pull/431
- 1.18 has been out of official support since 2023-02-01, when 1.20 was released
- bump minimum go version to 1.19
- run `go mod tidy`
=> maint: drop go 1.18

.circleci/config.yml
Adds golang 1.22 to test matrix versions.
- Add 1.22 to list of go versions in circle CI
=> maint: Add golang 1.22 to test matrix

trace/context.go
- Adhere to format Pyroscope OSS expects per https://github.com/grafana/otel-profiling-go/commit/207e85a83187411fc33a161f38b64e90289e6302#diff-e4d4c63738d3e4e1bf4f34e59bf9df3dfc89e9eae421f2345b98dd4535125903
We've switched to using Pyroscope OSS internally rather than Pyroscope/Grafana Cloud, so we need to use the format that the current profiling solution expects for how span names are tagged when doing correlation of span and profile signals.
=> feat(trace): update profileIDLabelName to match Pyroscope

.github/dependabot.yml
- Dependabot is complaining telemetry-team no longer exists
- s/telemetry/pipeline/
=> chore(dependabot): update team name
