- wrappers/hnygorilla/gorilla.go
- wrappers/hnygorilla/gorilla_test.go
> Record the struct name if the handler is a struct

- trace/trace.go
- trace/trace_test.go
When headers are serialized, the trace level fields are read, so we need
to take a read lock on those fields.
> This removes a race when serializing headers.

- trace/trace.go
The current code has the following deadlock potential when using sync spans in a async code.
If both child and parent spans' `.Send()` is called at roughly the same time, there is this possible ordering:
in goroutine1, sending parent:
1. Parent's `sendLock` is held (top of `.Send()`)
2. Parent's `childrenLock` is held, as it iterates child spans, to gather unsent sync spans.
3. Parent attempts to acquire `child.sendLock` (with an RLock).
Parent holds: `parent.childrenLock`
Parent wants: `child.sendLock`
in goroutine2, sending child
1. Child's `sendLock` is held (top of `.Send()`)
2. Child makes it all the way through the `.Send()` method, then calls `parent.removeChildSpan()`
3. `parent.removeChildSpan()` attempts to acquire `parent.childrenLock`
Child holds: `child.sendLock`
Child wants: …
> fix potential deadlock when using sync spans in async code

- examples/echo/README.md
- examples/echo/main.go
- wrappers/hnyecho/README.md
- wrappers/hnyecho/doc.go
- wrappers/hnyecho/echo.go
- wrappers/hnyecho/echo_test.go
- wrappers/hnyecho/hnyecho_test.go
Added a honeycomb instrumentation for the Echo router (https://echo.labstack.com/) via middleware
> New middleware for Echo router

- wrappers/hnyecho/echo_test.go
Tests were failing because the beeline wasn't being initialized. When `NewTrace` is called (in the common http call) on an uninitialized beeline, it uses the DiscardTransmission instead of handing them to libhoney. Even though libhoney was being initialized with the `MockOutput`, it was never being used as the transmission for the beeline.
This change initializes the beeline with a `MockTransmission` instead of libhoney.
> bringing hnyecho forward to the libhoney client world

- beeline_test.go
- trace/trace.go
- trace/trace_test.go
Reduces allocations from 10 to 8 when a new span is created. It's not a huge win but there's no real downside.
> reduce heap allocation when creating spans

- wrappers/hnyecho/echo.go
- wrappers/hnyecho/echo_test.go
- wrappers/hnyecho/hnyecho_test.go
Update to the latest release of Echo
> #69 - Echo middleware incompatible with v4

- .circleci/config.yml
- CHANGELOG.md
- version.go
- wrappers/common/common.go
- wrappers/common/common_go1.11.go
- wrappers/common/common_prego1.11.go
- wrappers/common/common_test.go
- wrappers/hnysql/sql.go
- wrappers/hnysql/sql_test.go
- wrappers/hnysqlx/sqlx.go
- wrappers/hnysqlx/sqlx_test.go
Add database stats from sql.DBStats to database calls to help understand database state.
> First pass at go database stats

- wrappers/hnynethttp/nethttp.go
Knowing what's gzipped and what's not is helpful!
> Add content-encoding.

- version.go
(should this be v0.5 as it's the first to use Go modules?)
> version bump to v0.5.0

- CHANGELOG.md
- version.go
> Version v0.6.1

- CHANGELOG.md
- version.go
> Version bump and changelog

- .circleci/config.yml
Noticed that we didn't have a GitHub release publish step, added one
> Add GitHub release publish step

- CHANGELOG.md
- version.go
Prepare v1.3.1 release.
- update version in version.go
- add changelog entry
> Prepare v1.3.1 release

- sample/deterministic_sampler_test.go
- https://github.com/honeycombio/beeline-go/issues/269#issuecomment-965812960
- closes #269
> test: remove flake-prone test case

- CHANGELOG.md
- Prepare release v1.3.2
- Update changelog with changes in v1.3.2
- Update header level in changelog for consistency
> Prepare release v1.3.2

- CHANGELOG.md
- version.go
Prepares the v1.4.1 release.
- Updates version to 1.4.1
> Prepare v1.4.1 release

- wrappers/hnysqlx/sqlx.go
- The `Rebind` method in the `hnysqlx` wrapper doesn't currently take a `context.Context` parameter, which results in events being sent as single-span traces outside the existing trace context:
- This PR adds a `RebindContext(ctx context.Context, query string) string` method to the `DB` struct. The new method just wraps `Rebind` but uses `BuildDBSpan` which can take a context. The result is that `Rebind` spans will be included in the trace context. Hooray! 
Fixes #59
> Add a RebindContext method to hnysqlx.DB wrapper

- CHANGELOG.md
- version.go
Prepares the v1.5.0 release.
- Update version to 1.5.0
> Prepare 1.5.0 release

- CHANGELOG.md
- version.go
Prepare the v1.5.1 release.
- Updates version to 1.5.1
> Prepare v1.5.1 release

- CHANGELOG.md
- version.go
> prepare 1.6.0 release

- CHANGELOG.md
- version.go
- new release with support for e&s
- updates changelog
- updates version from 1.6.0 to 1.7.0
> prepare release v1.7.0

- CHANGELOG.md
- go.sum
- version.go
> Prep for v1.8.0 release

- CHANGELOG.md
- version.go
Prepares the v1.9.0 release.
- Updates version to 1.9.0
> Prepare v1.9.0 release

- CHANGELOG.md
- version.go
- General releasery with the added spice to get #341 into the hands of users.
- Bumped version in version.go
- Updated CHANGELOG
> [release] prep v1.10.0

- CHANGELOG.md
- version.go
- Release v1.11.0
- Bump version
- Update changelog
> [release] v1.11.0

- CHANGELOG.md
- version.go
Prepares the v1.11.1 release
- Updates beeline version to 1.11.1
> Prepare v1.11.1 release

- CHANGELOG.md
- version.go
Prepares the v1.12.0 release.
- Updates version to 1.12.0
> rel: Prepare v1.12.0 release

- CHANGELOG.md
- version.go
> rel: prepare release 1.13.0

- CHANGELOG.md
- version.go
Prepares the next release of beeline-go library.
- Add changelog entry
- Update version to 1.16.0
> rel: Prepare v1.16.0 release

- CHANGELOG.md
- version.go
Prepares the next release of this package for publishing.
- Add changelog entry
- Update version to 1.17.0
> rel: Prepare v1.17.0 release

- .circleci/config.yml
> maint(build): add 1.23 to supported versions

- CHANGELOG.md
- version.go
Prepares the next release of beeline-go.
- Add changelog entry
- Update version to 1.18.0
> rel: Prepare v1.18.0 release

- CHANGELOG.md
- version.go
> rel: Prep v1.19.0
